import Head from 'next/head'
import styled from 'styled-components'
import HomeNavbar from "../components/HomeNavbar";

const Container = styled.div`
`

const WaitingListCard = styled.div`
  
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
            <HomeNavbar/>
            <Container>
                <WaitingListCard>
                    Join the Waiting list
                </WaitingListCard>
                {/*<Heading>*/}
                {/*    */}
                {/*</Heading>*/}
            </Container>
      </main>
    </>
  )
}
